name: Gradle CI

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]
        os: [ 'ubuntu-latest' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: "Gradle build"
        shell: bash
        run: |
          java -version
          javac -version
          ./gradlew --no-daemon build

      - name: Publish Build
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-${{ github.run_number }}-${{ matrix.java }}
          path: ${{ github.workspace }}